"""Initial migration

Revision ID: 77866ebe91d5
Revises: 
Create Date: 2026-02-06 17:18:35.031329+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77866ebe91d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('promo_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_code', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ASSIGNED', name='code_status'), nullable=False),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_codes_assigned_to_user_id'), 'promo_codes', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_promo_codes_raw_code'), 'promo_codes', ['raw_code'], unique=True)
    op.create_index(op.f('ix_promo_codes_status'), 'promo_codes', ['status'], unique=False)
    op.create_index('ix_promo_codes_status_assigned', 'promo_codes', ['status', 'assigned_to_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_promo_codes_status_assigned', table_name='promo_codes')
    op.drop_index(op.f('ix_promo_codes_status'), table_name='promo_codes')
    op.drop_index(op.f('ix_promo_codes_raw_code'), table_name='promo_codes')
    op.drop_index(op.f('ix_promo_codes_assigned_to_user_id'), table_name='promo_codes')
    op.drop_table('promo_codes')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
